### ISSUE TITLE
Potential additional locale data source

### ISSUE THREAD

**Issue by drbyte** [InvolvedGroup/laravel-lang-country#41]
Hi,
One package I've used in various applications, which provides a very comprehensive set of locale data, is https://github.com/mledoze/countries
Perhaps using its data may allow your package to expand its reach.

**Comment by stefro** [comment]
Thanks @drbyte! I'm familiar with the package, I've used it before on a project, and it has a lot of valuable data. This package focuses on the data about a country, and the LangCountry package focuses more or less on the customs of a country, specifically the date notations and languages. Of course there is some overlap, (naming, currency, etc) but I try to keep the package as light as possible.

I do appreciate your comment and added the package as a resource on the [contribution](https://stefro.github.io/laravel-lang-country/contribute/country-info.html) page in the documentation because it can be very helpful.
