### ISSUE TITLE
How to install when using Breeze or Jetstream as the installation instructions is not covering these

### ISSUE THREAD

**Issue by rabol** [InvolvedGroup/laravel-lang-country#43]
## Detailed description

The installation instructions tell one to add some code to the ```app\Http\Controllers\Auth\LoginController.php``` which does not exists if you use Laravel Breeze ot Laravel Jetstream

Adding the middleware will make the app fail with this exception:

```
Exception
The lang_country session is not set
```

also the section with the middleware could need a update, I believe that ```LangCountrySession::class```should be added 
Not sure if this should be treated as a enhancement or a question.

## Context

I'm pretty sure may other users would benefit from updated documentation

## Possible implementation

Update the documentation to support Laravel Breeze and Laravel Jetstream

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used PHP 8.2.11, Laravel 10.28
* Operating system and version (e.g. MacOS ventura):

**Comment by stefro** [comment]
@rabol Thank you for raising this issue. The `app\Http\Controllers\Auth\LoginController.php` is indeed an old controller type that was used before breeze/jetstream came along. The package is 6 years old and I haven't considered updating this in the documentation. You're right that this needs to be done in a next update.

In the Jetstream documentation, there is a section
https://jetstream.laravel.com/features/authentication.html#customizing-the-authentication-process where you can probably hook into to create the same result.

I will update the LangCountry documentation as soon as I can find some time to do so. In the meantime, if you've got it working with the Fortify docs, I'm happy to accept a PR on the LangCountry docs 😉.

**Comment by stefro** [comment]
@rabol 

**Breeze/Jetstream**
The code that needs to be added to the app\Http\Controllers\Auth\LoginController.php is now optional. By default, the package will now listen to the `Illuminate\Auth\Events\Login` event. When this event is fired, the package
will set the right sessions for the newly logged-in user based on the users database preferences.
The `Illuminate\Auth\Events\Login` event is dispatched when you're using the default Laravel authentication system (
Breeze/Jetstream).

This new behavior will be added with https://github.com/stefro/laravel-lang-country/pull/45 and will be deployed in version 3.1.0

**Exception**
The exception probably has a different cause. It is only thrown when the content of your session `lang_country` is `null`. This is probably caused by tinkering in development. Please clear your sessions and try again after proper implementation of the package

**Middleware**
> also the section with the middleware could need a update, I believe that LangCountrySession::classshould be added
Not sure if this should be treated as a enhancement or a question.

There is no need for this. In the documentation the 'lang_country' is suggested, which is a middlewareAlias for `LangCountrySession::class`.
https://github.com/stefro/laravel-lang-country/blob/933f00fdbe9c46fec39ae16f5b2a901203ed95d9/src/LaravelLangCountryServiceProvider.php#L21-L23
